version: '3.8'
services:
  bookmark:
    build:
      context: ./
    ports:
      - 5000:5000
    # command: flask db upgrade
    environment:
      - PYTHONBUFFERED=1
      - DATABASE_URL=postgresql://bm_user:pass@db:5432/bookmark

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bm_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bookmark

volumes:
  postgres_data:
